USE [master]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Type](
	[TypeNum] [int] NOT NULL,
	[CType] [nvarchar] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TypeNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[CID] [int] NOT NULL,
	[CPasswd] [nvarchar] NOT NULL,
	[CTitle] [nvarchar] NOT NULL,
	[CFname] [nvarchar] NOT NULL,
	[CLname] [nvarchar] NOT NULL,
	[CIC] [nvarchar] NOT NULL,
	[CNationality] [nvarchar] NOT NULL,
	[CContact] [nvarchar] NOT NULL,
	[CEmail] [nvarchar] NOT NULL,
	[CBankAcc] [nvarchar] NOT NULL,
	[CBank] [nvarchar] NOT NULL,
	[TypeNum] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admin](
	[AdID] [int] NOT NULL,
	[AdPasswd] [nvarchar] NOT NULL,
	[AdName] [nvarchar] NOT NULL,
	[AdContact] [nvarchar] NOT NULL,
	[AdEmail] [nvarchar] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AdID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reservation](
	[RxNum] [int] NOT NULL,
	[CIN] [nvarchar] NOT NULL,
	[COUT] [nvarchar] NOT NULL,
	[NON] [nvarchar] NOT NULL,
	[Status] [nvarchar] NOT NULL,
	[CID] [int] NOT NULL,
	[AdID] [int] NOT NULL,
	[RmID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RxNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Room](
	[RmID] [int] NOT NULL,
	[RmType] [nvarchar] NOT NULL,
	[RmBedding] [nvarchar] NOT NULL,
	[RmPrice] [nvarchar] NOT NULL,
	[RmStatus] [nvarchar] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RmID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Invoice](
	[INum] [int] NOT NULL,
	[TotalFee] [nvarchar] NOT NULL,
	[Description] [nvarchar] NOT NULL,
	[Date] [date] NOT NULL,
	[RxNum] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[INum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rating](
	[RatingID] [int] NOT NULL,
	[Rating] [nvarchar] NOT NULL,
	[RmID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RatingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Type]  WITH CHECK ADD FOREIGN KEY([TypeNum])
REFERENCES [dbo].[Customer] ([TypeNum])
GO
ALTER TABLE [dbo].[Admin]  WITH CHECK ADD FOREIGN KEY([AdIn])
REFERENCES [dbo].[Reservation] ([AdIn])
GO
ALTER TABLE [dbo].[Customer]  WITH CHECK ADD FOREIGN KEY([CID])
REFERENCES [dbo].[Reservation] ([CID])
GO
ALTER TABLE [dbo].[Room]  WITH CHECK ADD FOREIGN KEY([RmID])
REFERENCES [dbo].[Reservation] ([RmID])
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD FOREIGN KEY([RxNum])
REFERENCES [dbo].[Invoice] ([RxNum])
GO
ALTER TABLE [dbo].[Room]  WITH CHECK ADD FOREIGN KEY([RmID])
REFERENCES [dbo].[Rating] ([RmID])
GO