USE [master]
GO

/****** Object:  Database [ArendaTC_]    Script Date: 18.01.2022 13:32:07 ******/
CREATE DATABASE [ArendaTC_]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ArendaTC_', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ArendaTC_.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ArendaTC__log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ArendaTC__log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ArendaTC_].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ArendaTC_] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ArendaTC_] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ArendaTC_] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ArendaTC_] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ArendaTC_] SET ARITHABORT OFF 
GO

ALTER DATABASE [ArendaTC_] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ArendaTC_] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ArendaTC_] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ArendaTC_] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ArendaTC_] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ArendaTC_] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ArendaTC_] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ArendaTC_] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ArendaTC_] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ArendaTC_] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ArendaTC_] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ArendaTC_] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ArendaTC_] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ArendaTC_] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ArendaTC_] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ArendaTC_] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ArendaTC_] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ArendaTC_] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ArendaTC_] SET  MULTI_USER 
GO

ALTER DATABASE [ArendaTC_] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ArendaTC_] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ArendaTC_] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ArendaTC_] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ArendaTC_] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ArendaTC_] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ArendaTC_] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ArendaTC_] SET  READ_WRITE 
GO

